# --- Build Stage ---
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .
COPY .env .env
RUN yarn build

# --- Serve Stage ---
FROM node:20-alpine AS runner

WORKDIR /app
COPY --from=builder /app/dist ./dist

# Cài serve để xử lý routing fallback
RUN yarn global add serve

EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
