# backend/Dockerfile

FROM node:18-alpine AS builder

WORKDIR /app
COPY . .

RUN yarn install
RUN yarn build

FROM node:18-alpine

WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/yarn.lock ./yarn.lock

RUN yarn install --production

EXPOSE 8000
CMD ["node", "dist/server.js"]
