version: '3.8'

services:
 backend:
  build:
   context: ../backend
   dockerfile: Dockerfile
  ports:
   - '8000:8000'
  env_file:
   - ../backend/.env
  depends_on:
   - mongo

 frontend:
  build:
   context: ../frontend
   dockerfile: Dockerfile
  ports:
   - '5173:5173'
  env_file:
   - ../frontend/.env

 mongo:
  image: mongo:6
  volumes:
   - mongo_data:/data/db

volumes:
 mongo_data:
